default: &default
  adapter: postgresql
  pool: 5
  encoding: unicode
  timeout: 5000

development:
  <<: *default
  database: luv-notes_development

test:
  <<: *default
  database: luv-notes_test

production:
  <<: *default
  database: luv-notes_production
